/// Static BA identifier → human-readable label table.
pub(crate) const BA_LABELS: &[(&str, &str)] = &[
    // Western Interconnection
    ("CISO", "California ISO"),
    ("BPAT", "Bonneville Power Admin"),
    ("PACW", "PacifiCorp West"),
    ("PACE", "PacifiCorp East"),
    ("IPCO", "Idaho Power"),
    ("NEVP", "NV Energy"),
    ("AZPS", "Arizona Public Service"),
    ("SRP",  "Salt River Project"),
    ("WACM", "WAPA Colorado"),
    ("PSCO", "Xcel Energy Colorado"),
    ("AVA",  "Avista Corporation"),
    ("DOPD", "Douglas County PUD"),
    ("GCPD", "Grant County PUD"),
    ("CHPD", "Chelan County PUD"),
    ("TPWR", "City of Tacoma"),
    ("SCL",  "Seattle City Light"),
    ("PSEI", "Puget Sound Energy"),
    ("PGE",  "Portland General Electric"),
    ("PNM",  "Public Service NM"),
    ("EPE",  "El Paso Electric"),
    ("TEPC", "Tucson Electric Power"),
    ("IID",  "Imperial Irrigation District"),
    ("LDWP", "LA Dept of Water & Power"),
    ("BANC", "Balancing Auth of N. California"),
    ("TIDC", "Turlock Irrigation District"),
    ("NWMT", "Northwestern Energy MT"),
    ("GWA",  "NaturEner Wind Watch MT"),
    ("WALC", "WAPA Desert Southwest"),
    ("DEAA", "Arlington Valley LLC"),
    ("HGMA", "Harquahala Generating"),
    // Texas
    ("ERCO", "ERCOT (Texas)"),
    // Eastern Interconnection
    ("MISO", "Midcontinent ISO"),
    ("PJM",  "PJM Interconnection"),
    ("SWPP", "Southwest Power Pool"),
    ("TVA",  "Tennessee Valley Authority"),
    ("SOCO", "Southern Company"),
    ("DUK",  "Duke Energy"),
    ("CPLE", "Duke Energy Progress East"),
    ("CPLW", "Duke Energy Progress West"),
    ("SC",   "Santee Cooper"),
    ("SCEG", "Dominion Energy SC"),
    ("FPL",  "Florida Power & Light"),
    ("FPC",  "Duke Energy Florida"),
    ("TEC",  "Tampa Electric"),
    ("FMPP", "FL Municipal Power Pool"),
    ("GVL",  "Gainesville Regional Utilities"),
    ("HST",  "City of Homestead FL"),
    ("JEA",  "Jacksonville Electric Auth"),
    ("TAL",  "City of Tallahassee FL"),
    ("SEPA", "Southeastern Power Admin"),
    ("LGEE", "LG&E and KU Energy"),
    ("AECI", "Associated Electric Coop"),
    ("OVEC", "Ohio Valley Electric Corp"),
    ("EDE",  "Empire District Electric"),
    ("SPA",  "Southwestern Power Admin"),
    ("WAUW", "WAPA Upper Great Plains"),
    ("BHBA", "Black Hills Energy"),
    ("WWA",  "NaturEner Rim Rock MT"),
    ("SEC",  "Seminole Electric"),
    ("NYIS", "New York ISO"),
    ("ISNE", "ISO New England"),
    // Canada / Mexico
    ("HQT",  "Hydro-Québec"),
    ("IESO", "Ontario IESO"),
    ("MHEB", "Manitoba Hydro"),
    ("NBSO", "NB System Operator"),
    ("AESO", "Alberta Electric System"),
    ("BCHA", "BC Hydro"),
    ("CEN",  "CFE Mexico"),
    ("CFE",  "CFE Mexico"),
];
